bench: fix CaseFolding.txt.15 make rules
the 3 jobs all created a CaseFolding.txt.15 which merged together
(wget does not lock apparently), creating havoc

diff --git a/Makefile.PL b/Makefile.PL
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -28,19 +28,22 @@ my $clean = {
 };
 my $MM_VER = ExtUtils::MakeMaker->VERSION;
 WriteMakefile(
-    'AUTHOR'   => 'Reini Urban <rurban@cpan.org>',
-    'ABSTRACT' => 'Generate Unicode Case Transformation Tables',
-
-    # see perl5110delta, @INC reorganization
-    'INSTALLDIRS'  => ( $] >= 5.007002 && $] < 5.011 ) ? 'perl' : 'site',
+    'AUTHOR'       => 'Reini Urban <rurban@cpan.org>',
+    'ABSTRACT'     => 'Generate Unicode Case Transformation Tables',
+    'INSTALLDIRS'  => 'site',
     'LICENSE'      => 'perl',
     'NAME'         => 'Unicode::Towctrans',
     'VERSION_FROM' => $BIN,
     'clean'        => $clean,
     'PREREQ_PM'    => {
-        Carp     => 0,
-        strict   => 0,
-        warnings => 0,
+        Carp         => 0,
+        strict       => 0,
+        warnings     => 0,
+        Config       => 0,
+        constant     => 0,
+        Getopt::Long => 0,
+        Unicode::UCD => 0,
+        Test::More   => 0,
     },
     ( $MM_VER < 6.48 ? () : MIN_PERL_VERSION => 5.6.0 ),
     (   $MM_VER < 6.46
@@ -83,7 +86,7 @@ package MY;
 
 sub depend {
     '
-.PHONY: tidy test-all diffs examples release-test release
+.PHONY: tidy test-all diffs examples release-test release update-bench
 all :: towctrans.h README
 ' . (   $^O eq 'MSWin32'
         ? ""
@@ -97,6 +100,7 @@ test-precommit :
 '
         ) . '
 README: bin/gen_wctrans
+	make -C examples update-bench
 	pod2text $< >$@
 tidy:
 	perltidy -b bin/gen_wctrans
@@ -106,11 +110,10 @@ CaseFolding.txt.8 towctrans-8.h CaseFolding.txt.15:
 	for v in `seq 5 18`; do $(FULLPERLRUN) bin/gen_wctrans --out towctrans-$$v.h -v $$v --cf CaseFolding.txt.$$v; done
 test-all : bin/gen_wctrans CaseFolding.txt.8 towctrans-8.h
 	for v in `seq 5 18`; do \
-          $(FULLPERLRUN) bin/gen_wctrans --out towctrans.h -v $$v --cf CaseFolding.txt; \
-          echo Unicode $$v; \
-          $(FULLPERLRUN) -MExtUtils::Command::MM -MTest::Harness -e "test_harness(0)" t/*.t; \
-        done; \
-        $(FULLPERLRUN) bin/gen_wctrans --out towctrans.h
+	  $(FULLPERLRUN) bin/gen_wctrans --out towctrans.h -v $$v --cf CaseFolding.txt; \
+	  echo Unicode $$v; \
+	  $(FULLPERLRUN) -MExtUtils::Command::MM -MTest::Harness -e "test_harness(0)" t/*.t; done; \
+	$(FULLPERLRUN) bin/gen_wctrans --out towctrans.h
 diffs : bin/gen_wctrans CaseFolding.txt.8
 	for v in `seq 5 17`; do n=$$(($$v + 1)); diff -bu towctrans-$$v.h towctrans-$$n.h; done
 towctrans.h: bin/gen_wctrans
@@ -119,22 +122,24 @@ towctrans-15.h:
 	$(FULLPERLRUN) bin/gen_wctrans --out towctrans-15.h -v 15 --cf CaseFolding.txt.15
 bench: towctrans-15.h
 	make -C examples bench
+update-bench:
+	make -C examples $@
 examples:
 	make -C examples
 release-test : test dist
 	if test "$(shell git rev-parse --abbrev-ref HEAD)" != "master" || \
-           test "$(shell git diff --raw)" != "" || \
-           test "$(shell git diff --cached --raw)" != "" ; then \
-          echo "You are not on a clean master branch, aborting."; \
-          exit 1; \
+	  test "$(shell git diff --raw)" != "" || \
+	  test "$(shell git diff --cached --raw)" != "" ; then \
+	  echo "You are not on a clean master branch, aborting."; \
+	  exit 1; \
 	fi
 	if test "$(shell git ls --show-signature -n 1 | head -n2 | tail -n1 | cut -c1-5)" != "gpg: " ; then \
-            echo "need git commit with -S"; \
-            exit 1; \
+	  echo "need git commit with -S"; \
+	  exit 1; \
 	fi
 	if test "$(shell git ls --no-show-signature -n 1 | head -n5 | tail -n1 | cut -c5-11)" != "Release" ; then \
-            echo "need git commit with -m Release"; \
-            exit 1; \
+	  echo "need git commit with -m Release"; \
+	  exit 1; \
 	fi
 
 release : release-test
